apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: microservices
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS userdb;
    CREATE DATABASE IF NOT EXISTS orderdb;
    CREATE DATABASE IF NOT EXISTS notificationdb;
