apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
data:
  # echo -n "super-secret-jwt-key-change-in-production" | base64
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=
  # echo -n "rootpassword" | base64
  mysql-root-password: cm9vdHBhc3N3b3Jk
